services:
  test_mysql:
    container_name: test_mysql
    image: mysql:8.0.35
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./init_sql/:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql 
volumes:
  mysql_data:
      