-- 데이터베이스의 모든 인덱스 확인
SELECT DISTINCT
    TABLE_NAME,
    INDEX_NAME,
    GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS indexed_columns
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = 'employees'
GROUP BY TABLE_NAME, INDEX_NAME;